POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Why Facts Don’t Change Our Minds",
  "author": "James Clear",
  "url": "https://jamesclear.com/why-facts-dont-change-minds",
  "likes": 35536
}
