POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Test 2",
  "author": "me 2",
  "url": "https://www.example2.com",
  "likes": 82
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "qwertya",
    "name": "Petroa",
    "password": "helloa"
}